# You will need NFS storage class, or any other ReadWriteMany storageclass
# Quick and easy way to get it is https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: models
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: download
spec:
  template:
    spec:
      containers:
      - name: tensorflow
        image: inc0/issues
        command: ["/issues/download_data.sh", "https://storage.googleapis.com/kubeflow-examples/github-issue-summarization-data/github-issues.zip", "/data"]
        volumeMounts:
        - name: data
          mountPath: "/data"
        - name: models
          mountPath: "/model"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: models
          persistentVolumeClaim:
            claimName: models
      restartPolicy: Never
  backoffLimit: 4

---
apiVersion: "kubeflow.org/v1alpha2"
kind: TFJob
metadata:
  name: github
spec:
  tfReplicaSpecs:
    Master:
      replicas: 1
      template:
        spec:
          containers:
          - name: tensorflow
            image: inc0/issues
            command: ["python", "/issues/train.py"]
            volumeMounts:
            - name: data
              mountPath: "/data"
            - name: models
              mountPath: "/model"
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: data
            - name: models
              persistentVolumeClaim:
                claimName: models
    Worker:
      replicas: 5
      template:
        spec:
          containers:
          - name: tensorflow
            image: inc0/issues
            command: ["python", "/issues/train.py"]
            volumeMounts:
            - name: data
              mountPath: "/data"
            - name: models
              mountPath: "/model"
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: data
            - name: models
              persistentVolumeClaim:
                claimName: models
    PS:
      replicas: 3
      template:
        spec:
          containers:
          - name: tensorflow
            image: inc0/issues
            command: ["python", "/issues/train.py"]
            volumeMounts:
            - name: data
              mountPath: "/data"
            - name: models
              mountPath: "/model"
            ports:
            - containerPort: 6006
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: data
            - name: models
              persistentVolumeClaim:
                claimName: models
